### ISSUE TITLE
AttributeError: 'module' object has no attribute 'packet_encoder'

### ISSUE THREAD

**Issue by Yash-dev1** [Thmz/gnuradioproject#2]
When I try to run the encdec_custom_fec.grc example, I get the following error:
`Generating: '/home/dragon/gr-packetizer/examples/encdec_custom_fec.py`
`Executing: /usr/bin/python -u /home/dragon/gr-packetizer/examples/encdec_custom_fec.py`
`Using Volk machine: avx2_64_mmx_orc
Traceback (most recent call last):
  File "/home/dragon/gr-packetizer/examples/encdec_custom_fec.py", line 432, in <module>`
`    main()
  File "/home/dragon/gr-packetizer/examples/encdec_custom_fec.py", line 420, in main
    tb = top_block_cls(frame_size=options.frame_size, puncpat=options.puncpat)
  File "/home/dragon/gr-packetizer/examples/encdec_custom_fec.py", line 240, in __init__`
`    self.packetizer_packet_encoder_0 = packetizer.packet_encoder((preamble), constel_header.base(), constel_payload.base(), header_formatter.base(), False, False, "packet_len", 0, False, 1)`
`AttributeError: 'module' object has no attribute 'packet_encoder'`
I'm using GNU Radio Companion 3.7.9 on Ubuntu 16.04. I dont know how to resolve this issue.Any leads will be thankful

**Comment by josephjosuuu** [comment]
Have you installed the gr-packetizer module?
